"""
controlador.py — Controller Process for the Greenhouse System.

Responsibilities:
  1. Boot-time State Transfer: queries the Middleware Server for the
     majority-approved state before consuming MQTT messages.
  2. MQTT Subscription: receives temperature and humidity readings.
  3. Decision Logic: activates pump and exhaust fan per thresholds.
  4. JSON Persistence: saves current state to a local file.
  5. XML-RPC Server: exposes remote methods to the Middleware (internal cluster API).

MQTT Deduplication: Each MQTT command payload includes a 'comando_id' (UUID)
generated by the Middleware. The actuator deduplicates using this ID.

Startup Sequence:
    1. Start XML-RPC server in a background thread (so Middleware can reach us)
    2. Query Middleware Server to sync state (with retries)
    3. Start MQTT client to consume sensor data

Usage:
    python -m estufa.controlador --id ctrl_1 --port 8001 --data data_ctrl_1.json
    python -m estufa.controlador --id ctrl_2 --port 8002 --data data_ctrl_2.json
    python -m estufa.controlador --id ctrl_3 --port 8003 --data data_ctrl_3.json

    # Byzantine mode (for fault demonstration):
    python -m estufa.controlador --id ctrl_2 --port 8002 --data data_ctrl_2.json --byzantino
"""

import argparse
import json
import os
import threading
import time
import hashlib
import xmlrpc.client
from xmlrpc.server import SimpleXMLRPCServer, SimpleXMLRPCRequestHandler
import paho.mqtt.client as mqtt
from estufa import config


# ─────────────────────────────────────────
# Default state
# ─────────────────────────────────────────
ESTADO_INICIAL = {
    "temperatura": None,
    "umidade_solo": None,
    "bomba_ligada": False,
    "exaustor_ligado": False,
    "ultima_atualizacao": None,
    "sensor_timestamp": None,
    "controlador_id": None,
}


class Controlador:
    """
    Greenhouse process controller node.

    Thread-safe: lock protects shared state between MQTT thread (writes)
    and XML-RPC server thread (reads).
    """

    def __init__(self, ctrl_id: str, data_file: str, byzantino: bool = False):
        """
        Args:
            ctrl_id: Unique identifier for this controller (e.g. 'ctrl_1').
            data_file: Path to the JSON persistence file.
            byzantino: If True, returns deliberately wrong data (fault simulation).
        """
        self.ctrl_id = ctrl_id
        self.data_file = data_file
        self.byzantino = byzantino
        self._lock = threading.Lock()
        self._mqtt_client = None

        # Load state from disk or use initial state
        self._estado = self._carregar_estado()
        self._estado["controlador_id"] = ctrl_id

    # ─── Persistence ────────────────────────────────────────────

    def _carregar_estado(self) -> dict:
        """Reads current state from JSON file. Returns initial state if file missing."""
        if os.path.exists(self.data_file):
            try:
                with open(self.data_file, "r", encoding="utf-8") as f:
                    return json.load(f)
            except (json.JSONDecodeError, IOError):
                pass
        return dict(ESTADO_INICIAL)

    def _salvar_estado(self) -> None:
        """Persists current state to JSON file (must be called with lock held)."""
        try:
            with open(self.data_file, "w", encoding="utf-8") as f:
                json.dump(self._estado, f, indent=2, ensure_ascii=False)
        except IOError as e:
            print(f"[{self.ctrl_id}] Erro ao salvar estado: {e}")

    # ─── Boot-time State Synchronization ────────────────────────

    def _sincronizar_estado_via_middleware(self, max_tentativas: int = 10, intervalo: float = 2.0) -> bool:
        """
        Queries the Middleware Server for the majority-approved state and
        overwrites local JSON with it.

        This is called ONCE at startup before MQTT consumption begins.
        The Middleware must already be running on MIDDLEWARE_PORT.

        Args:
            max_tentativas: Maximum retry attempts if Middleware is unreachable.
            intervalo: Seconds to wait between retries.

        Returns:
            True if sync succeeded, False if all retries failed.
        """
        mw_url = f"http://{config.MIDDLEWARE_HOST}:{config.MIDDLEWARE_PORT}"
        print(f"[{self.ctrl_id}] 🔄 Iniciando sincronização de estado via Middleware ({mw_url})...")

        for tentativa in range(1, max_tentativas + 1):
            try:
                proxy = xmlrpc.client.ServerProxy(mw_url, allow_none=True)
                # Use the middleware's internal quorum-read (excludes this node if down)
                estado_majoritario = proxy.obter_estado()

                with self._lock:
                    # Preserve our controller_id, update everything else
                    estado_majoritario["controlador_id"] = self.ctrl_id
                    self._estado = estado_majoritario
                    self._salvar_estado()

                print(f"[{self.ctrl_id}] ✅ Estado sincronizado com sucesso (tentativa {tentativa}/{max_tentativas}).")
                print(f"[{self.ctrl_id}]    Bomba={self._estado.get('bomba_ligada')}, "
                      f"Exaustor={self._estado.get('exaustor_ligado')}, "
                      f"Temp={self._estado.get('temperatura')}")
                return True

            except Exception as e:
                print(f"[{self.ctrl_id}] ⚠️  Tentativa {tentativa}/{max_tentativas} — Middleware indisponível: {e}")
                if tentativa < max_tentativas:
                    time.sleep(intervalo)

        print(f"[{self.ctrl_id}] ⚠️  Sincronização falhou após {max_tentativas} tentativas. "
              f"Iniciando com estado local (pode estar desatualizado).")
        return False

    # ─── Decision Logic ──────────────────────────────────────────

    def _decidir_atuacao(self) -> None:
        """
        Evaluates current state and decides whether to activate/deactivate actuators.
        Publishes MQTT commands with a 'comando_id' generated by this controller.
        Must be called with the lock held.

        NOTE: The 'comando_id' is generated deterministically by hashing the action
        and the sensor's original MQTT timestamp. This ensures all 3 controllers
        generate the exact same ID, allowing the actuator to deduplicate.
        """
        temp    = self._estado.get("temperatura")
        umidade = self._estado.get("umidade_solo")
        sensor_ts = self._estado.get("sensor_timestamp", 0)

        def gerar_comando_id(acao_alvo):
            raw = f"{acao_alvo}_{sensor_ts}"
            return hashlib.md5(raw.encode("utf-8")).hexdigest()

        if temp is not None:
            if temp > config.TEMP_MAX_CELSIUS and not self._estado["exaustor_ligado"]:
                self._estado["exaustor_ligado"] = True
                cmd_id = gerar_comando_id("exaustor_ligar")
                self._publicar_comando(config.TOPIC_ATUADOR_EXAUSTOR, "ligar", cmd_id)
                print(f"[{self.ctrl_id}] 🌡️  Temp={temp:.1f}°C > {config.TEMP_MAX_CELSIUS}°C → LIGAR exaustor")
            elif temp < config.TEMP_MIN_CELSIUS and self._estado["exaustor_ligado"]:
                self._estado["exaustor_ligado"] = False
                cmd_id = gerar_comando_id("exaustor_desligar")
                self._publicar_comando(config.TOPIC_ATUADOR_EXAUSTOR, "desligar", cmd_id)
                print(f"[{self.ctrl_id}] 🌡️  Temp={temp:.1f}°C < {config.TEMP_MIN_CELSIUS}°C → DESLIGAR exaustor")

        if umidade is not None:
            if umidade < config.UMIDADE_MIN_PERCENT and not self._estado["bomba_ligada"]:
                self._estado["bomba_ligada"] = True
                cmd_id = gerar_comando_id("bomba_ligar")
                self._publicar_comando(config.TOPIC_ATUADOR_BOMBA, "ligar", cmd_id)
                print(f"[{self.ctrl_id}] 💧 Umidade={umidade:.1f}% < {config.UMIDADE_MIN_PERCENT}% → LIGAR bomba")
            elif umidade > config.UMIDADE_MAX_PERCENT and self._estado["bomba_ligada"]:
                self._estado["bomba_ligada"] = False
                cmd_id = gerar_comando_id("bomba_desligar")
                self._publicar_comando(config.TOPIC_ATUADOR_BOMBA, "desligar", cmd_id)
                print(f"[{self.ctrl_id}] 💧 Umidade={umidade:.1f}% > {config.UMIDADE_MAX_PERCENT}% → DESLIGAR bomba")

    def _publicar_comando(self, topico: str, acao: str, comando_id: str) -> None:
        """Publishes a command to an actuator via MQTT, including the comando_id for deduplication."""
        payload = json.dumps({
            "acao": acao,
            "origem": self.ctrl_id,
            "comando_id": comando_id,
            "timestamp": time.time(),
        })
        if self._mqtt_client:
            self._mqtt_client.publish(topico, payload, qos=1)

    # ─── MQTT Callbacks ──────────────────────────────────────────

    def _on_connect(self, client, userdata, flags, reason_code, properties):
        if reason_code == 0:
            client.subscribe(config.TOPIC_TEMPERATURA,  qos=1)
            client.subscribe(config.TOPIC_UMIDADE_SOLO, qos=1)
            print(f"[{self.ctrl_id}] Conectado ao MQTT. Assinando tópicos de sensores.")
        else:
            print(f"[{self.ctrl_id}] Falha na conexão MQTT: {reason_code}")

    def _on_message(self, client, userdata, msg):
        try:
            payload = json.loads(msg.payload.decode("utf-8"))
            valor   = float(payload["valor"])
            sensor_ts = payload.get("timestamp", time.time())
        except (json.JSONDecodeError, KeyError, ValueError) as e:
            print(f"[{self.ctrl_id}] Mensagem inválida: {e}")
            return

        with self._lock:
            if msg.topic == config.TOPIC_TEMPERATURA:
                self._estado["temperatura"] = valor
                print(f"[{self.ctrl_id}] 🌡️  Temperatura recebida: {valor:.2f}°C")
            elif msg.topic == config.TOPIC_UMIDADE_SOLO:
                self._estado["umidade_solo"] = valor
                print(f"[{self.ctrl_id}] 💧 Umidade do solo recebida: {valor:.2f}%")

            self._estado["ultima_atualizacao"] = time.time()
            self._estado["sensor_timestamp"] = sensor_ts
            self._decidir_atuacao()
            self._salvar_estado()

    # ─── XML-RPC Methods (exposed to Middleware) ─────────────────

    def obter_estado(self) -> dict:
        """
        Returns the current greenhouse state.
        If in Byzantine mode, returns deliberately falsified data.
        """
        with self._lock:
            if self.byzantino:
                return {
                    "temperatura": 999.0,
                    "umidade_solo": -1.0,
                    "bomba_ligada": not self._estado.get("bomba_ligada", False),
                    "exaustor_ligado": not self._estado.get("exaustor_ligado", False),
                    "ultima_atualizacao": time.time(),
                    "sensor_timestamp": self._estado.get("sensor_timestamp"),
                    "controlador_id": self.ctrl_id,
                    "_byzantino": True,
                }
            return dict(self._estado)

    def comandar_bomba(self, acao: str, comando_id: str = "") -> dict:
        """
        Manual command: turn pump on or off.

        Args:
            acao: 'ligar' or 'desligar'
            comando_id: UUID generated by Middleware for deduplication at actuator level.

        Returns:
            dict with 'sucesso' (bool) and 'mensagem' (str).
        """
        acao = acao.lower().strip()
        if acao not in ("ligar", "desligar"):
            return {"sucesso": False, "mensagem": f"Ação inválida: '{acao}'. Use 'ligar' ou 'desligar'."}

        if self.byzantino:
            return {"sucesso": True, "mensagem": f"[BYZANTINO] Bomba {acao}da (FALSO)", "byzantino": True}

        with self._lock:
            novo_estado = (acao == "ligar")
            self._estado["bomba_ligada"] = novo_estado
            self._publicar_comando(config.TOPIC_ATUADOR_BOMBA, acao, comando_id)
            self._salvar_estado()
            return {"sucesso": True, "mensagem": f"Bomba {acao}da com sucesso pelo {self.ctrl_id}"}

    def comandar_exaustor(self, acao: str, comando_id: str = "") -> dict:
        """
        Manual command: turn exhaust fan on or off.

        Args:
            acao: 'ligar' or 'desligar'
            comando_id: UUID generated by Middleware for deduplication.

        Returns:
            dict with 'sucesso' (bool) and 'mensagem' (str).
        """
        acao = acao.lower().strip()
        if acao not in ("ligar", "desligar"):
            return {"sucesso": False, "mensagem": f"Ação inválida: '{acao}'. Use 'ligar' ou 'desligar'."}

        if self.byzantino:
            return {"sucesso": True, "mensagem": f"[BYZANTINO] Exaustor {acao}do (FALSO)", "byzantino": True}

        with self._lock:
            novo_estado = (acao == "ligar")
            self._estado["exaustor_ligado"] = novo_estado
            self._publicar_comando(config.TOPIC_ATUADOR_EXAUSTOR, acao, comando_id)
            self._salvar_estado()
            return {"sucesso": True, "mensagem": f"Exaustor {acao}do com sucesso pelo {self.ctrl_id}"}

    def ping(self) -> str:
        """Health-check used by the Middleware to detect alive replicas."""
        return f"pong:{self.ctrl_id}"

    # ─── Initialization ──────────────────────────────────────────

    def iniciar(self, host: str, port: int, skip_sync: bool = False) -> None:
        """
        Starts the controller in the correct boot sequence:

        1. Start XML-RPC server in a daemon thread (must be up so Middleware can see it)
        2. Perform boot-time state synchronization via Middleware (with retries)
        3. Connect to MQTT broker and begin consuming sensor data

        Args:
            host: Host for the XML-RPC server.
            port: Port for the XML-RPC server.
            skip_sync: If True, skip state sync (useful for testing or first boot before Middleware starts).
        """
        # ── Step 1: Start XML-RPC server in background ────────────────────────
        class SilentHandler(SimpleXMLRPCRequestHandler):
            """Suppresses HTTP logs from the XML-RPC server."""
            def log_message(self, fmt, *args):
                pass

        server = SimpleXMLRPCServer(
            (host, port),
            requestHandler=SilentHandler,
            allow_none=True,
            logRequests=False,
        )
        server.register_instance(self)
        server.register_introspection_functions()

        modo = " [MODO BYZANTINO]" if self.byzantino else ""
        print(f"[{self.ctrl_id}] XML-RPC server iniciado em {host}:{port}{modo}")

        server_thread = threading.Thread(target=server.serve_forever, daemon=True)
        server_thread.start()

        # ── Step 2: Boot-time State Synchronization ───────────────────────────
        if not skip_sync:
            self._sincronizar_estado_via_middleware()
        else:
            print(f"[{self.ctrl_id}] ⚠️  Sincronização de estado ignorada (--skip-sync ativo).")

        # ── Step 3: Connect to MQTT broker ────────────────────────────────────
        self._mqtt_client = mqtt.Client(
            mqtt.CallbackAPIVersion.VERSION2,
            client_id=f"controlador_{self.ctrl_id}"
        )
        self._mqtt_client.on_connect = self._on_connect
        self._mqtt_client.on_message = self._on_message
        self._mqtt_client.connect(config.MQTT_HOST, config.MQTT_PORT, config.MQTT_KEEPALIVE)

        print(f"[{self.ctrl_id}] ✅ Controlador totalmente inicializado. Consumindo sensores MQTT.")
        self._mqtt_client.loop_forever()  # Blocks here (main thread)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Controlador da Estufa")
    parser.add_argument("--id",        required=True,        help="Controller ID (e.g. ctrl_1)")
    parser.add_argument("--port",      required=True,        type=int, help="XML-RPC port")
    parser.add_argument("--data",      required=True,        help="JSON persistence file")
    parser.add_argument("--host",      default="localhost",  help="XML-RPC server host")
    parser.add_argument("--byzantino", action="store_true",  help="Byzantine mode (returns false data)")
    parser.add_argument("--skip-sync", action="store_true",  help="Skip boot-time state synchronization")
    args = parser.parse_args()

    ctrl = Controlador(ctrl_id=args.id, data_file=args.data, byzantino=args.byzantino)
    ctrl.iniciar(host=args.host, port=args.port, skip_sync=args.skip_sync)
