# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: carteira.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'carteira.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61rteira.proto\x12\x08\x63\x61rteira\" \n\x0c\x43ontaRequest\x12\x10\n\x08\x63onta_id\x18\x01 \x01(\t\"U\n\x10TransacaoRequest\x12\x10\n\x08\x63onta_id\x18\x01 \x01(\t\x12\r\n\x05valor\x18\x02 \x01(\x01\x12\x11\n\tdescricao\x18\x03 \x01(\t\x12\r\n\x05moeda\x18\x04 \x01(\t\"R\n\x11\x43riarContaRequest\x12\x10\n\x08\x63onta_id\x18\x01 \x01(\t\x12\x14\n\x0cnome_titular\x18\x02 \x01(\t\x12\x15\n\rsaldo_inicial\x18\x03 \x01(\x01\"O\n\x11TransferirRequest\x12\x14\n\x0c\x63onta_origem\x18\x01 \x01(\t\x12\x15\n\rconta_destino\x18\x02 \x01(\t\x12\r\n\x05valor\x18\x03 \x01(\x01\"L\n\x11TransacaoResponse\x12\x10\n\x08\x63onta_id\x18\x01 \x01(\t\x12\x13\n\x0bsaldo_atual\x18\x02 \x01(\x01\x12\x10\n\x08mensagem\x18\x03 \x01(\t\"L\n\rSaldoResponse\x12\x10\n\x08\x63onta_id\x18\x01 \x01(\t\x12\x14\n\x0cnome_titular\x18\x02 \x01(\t\x12\x13\n\x0bsaldo_atual\x18\x03 \x01(\x01\x32\xec\x02\n\x0f\x43\x61rteiraService\x12\x46\n\nCriarConta\x12\x1b.carteira.CriarContaRequest\x1a\x1b.carteira.TransacaoResponse\x12\x41\n\x0e\x43onsultarSaldo\x12\x16.carteira.ContaRequest\x1a\x17.carteira.SaldoResponse\x12\x44\n\tDepositar\x12\x1a.carteira.TransacaoRequest\x1a\x1b.carteira.TransacaoResponse\x12@\n\x05Sacar\x12\x1a.carteira.TransacaoRequest\x1a\x1b.carteira.TransacaoResponse\x12\x46\n\nTransferir\x12\x1b.carteira.TransferirRequest\x1a\x1b.carteira.TransacaoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'carteira_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTAREQUEST']._serialized_start=28
  _globals['_CONTAREQUEST']._serialized_end=60
  _globals['_TRANSACAOREQUEST']._serialized_start=62
  _globals['_TRANSACAOREQUEST']._serialized_end=147
  _globals['_CRIARCONTAREQUEST']._serialized_start=149
  _globals['_CRIARCONTAREQUEST']._serialized_end=231
  _globals['_TRANSFERIRREQUEST']._serialized_start=233
  _globals['_TRANSFERIRREQUEST']._serialized_end=312
  _globals['_TRANSACAORESPONSE']._serialized_start=314
  _globals['_TRANSACAORESPONSE']._serialized_end=390
  _globals['_SALDORESPONSE']._serialized_start=392
  _globals['_SALDORESPONSE']._serialized_end=468
  _globals['_CARTEIRASERVICE']._serialized_start=471
  _globals['_CARTEIRASERVICE']._serialized_end=835
# @@protoc_insertion_point(module_scope)
