# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import carteira_pb2 as carteira__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in carteira_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarteiraServiceStub:
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarConta = channel.unary_unary(
                '/carteira.CarteiraService/CriarConta',
                request_serializer=carteira__pb2.CriarContaRequest.SerializeToString,
                response_deserializer=carteira__pb2.TransacaoResponse.FromString,
                _registered_method=True)
        self.ConsultarSaldo = channel.unary_unary(
                '/carteira.CarteiraService/ConsultarSaldo',
                request_serializer=carteira__pb2.ContaRequest.SerializeToString,
                response_deserializer=carteira__pb2.SaldoResponse.FromString,
                _registered_method=True)
        self.Depositar = channel.unary_unary(
                '/carteira.CarteiraService/Depositar',
                request_serializer=carteira__pb2.TransacaoRequest.SerializeToString,
                response_deserializer=carteira__pb2.TransacaoResponse.FromString,
                _registered_method=True)
        self.Sacar = channel.unary_unary(
                '/carteira.CarteiraService/Sacar',
                request_serializer=carteira__pb2.TransacaoRequest.SerializeToString,
                response_deserializer=carteira__pb2.TransacaoResponse.FromString,
                _registered_method=True)
        self.Transferir = channel.unary_unary(
                '/carteira.CarteiraService/Transferir',
                request_serializer=carteira__pb2.TransferirRequest.SerializeToString,
                response_deserializer=carteira__pb2.TransacaoResponse.FromString,
                _registered_method=True)


class CarteiraServiceServicer:
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────

    """

    def CriarConta(self, request, context):
        """Creates a new account with an initial balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarSaldo(self, request, context):
        """Queries the balance and data of an existing account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Depositar(self, request, context):
        """Deposits a value into an account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sacar(self, request, context):
        """Withdraws a value from an account
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transferir(self, request, context):
        """Transfers a value between two accounts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarteiraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarConta': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarConta,
                    request_deserializer=carteira__pb2.CriarContaRequest.FromString,
                    response_serializer=carteira__pb2.TransacaoResponse.SerializeToString,
            ),
            'ConsultarSaldo': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarSaldo,
                    request_deserializer=carteira__pb2.ContaRequest.FromString,
                    response_serializer=carteira__pb2.SaldoResponse.SerializeToString,
            ),
            'Depositar': grpc.unary_unary_rpc_method_handler(
                    servicer.Depositar,
                    request_deserializer=carteira__pb2.TransacaoRequest.FromString,
                    response_serializer=carteira__pb2.TransacaoResponse.SerializeToString,
            ),
            'Sacar': grpc.unary_unary_rpc_method_handler(
                    servicer.Sacar,
                    request_deserializer=carteira__pb2.TransacaoRequest.FromString,
                    response_serializer=carteira__pb2.TransacaoResponse.SerializeToString,
            ),
            'Transferir': grpc.unary_unary_rpc_method_handler(
                    servicer.Transferir,
                    request_deserializer=carteira__pb2.TransferirRequest.FromString,
                    response_serializer=carteira__pb2.TransacaoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carteira.CarteiraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('carteira.CarteiraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarteiraService:
    """─────────────────────────────────────────────
    Service Definition
    ─────────────────────────────────────────────

    """

    @staticmethod
    def CriarConta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carteira.CarteiraService/CriarConta',
            carteira__pb2.CriarContaRequest.SerializeToString,
            carteira__pb2.TransacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarSaldo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carteira.CarteiraService/ConsultarSaldo',
            carteira__pb2.ContaRequest.SerializeToString,
            carteira__pb2.SaldoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Depositar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carteira.CarteiraService/Depositar',
            carteira__pb2.TransacaoRequest.SerializeToString,
            carteira__pb2.TransacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sacar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carteira.CarteiraService/Sacar',
            carteira__pb2.TransacaoRequest.SerializeToString,
            carteira__pb2.TransacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transferir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carteira.CarteiraService/Transferir',
            carteira__pb2.TransferirRequest.SerializeToString,
            carteira__pb2.TransacaoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
